### ISSUE TITLE
error related to SigProfilerAssignment requires pandas==1.5.3 

### ISSUE THREAD

**Issue by allaway** [AlexandrovLab/SigProfilerAssignment#132]
SigProfilerAssignment seems to depend on pandas-1.5.3. However, when this pandas is installed I get the error `ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject` when I try to import Analyzer. Upgrading to pandas-2.2.2 after install resolves this. 

example here:
```
Installing collected packages: pandas, SigProfilerAssignment
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
  Attempting uninstall: SigProfilerAssignment
    Found existing installation: SigProfilerAssignment 0.1.5
    Uninstalling SigProfilerAssignment-0.1.5:
      Successfully uninstalled SigProfilerAssignment-0.1.5
Successfully installed SigProfilerAssignment-0.1.7 pandas-1.5.3
[ec2-user@ip-10-41-24-211 jhu]$ python3
Python 3.9.16 (main, Sep  8 2023, 00:00:00)
[GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from SigProfilerAssignment import Analyzer as Analyze
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/.local/lib/python3.9/site-packages/SigProfilerAssignment/Analyzer.py", line 1, in <module>
    from SigProfilerAssignment import decomposition as decomp
  File "/home/ec2-user/.local/lib/python3.9/site-packages/SigProfilerAssignment/decomposition.py", line 16, in <module>
    from SigProfilerAssignment import decompose_subroutines as sub
  File "/home/ec2-user/.local/lib/python3.9/site-packages/SigProfilerAssignment/decompose_subroutines.py", line 13, in <module>
    import pandas as pd
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/compat/__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/home/ec2-user/.local/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by allaway** [comment]
Ah, but now I see that pandas>2.0.0 is not compatible with other steps (due to deprecation of `append`)

**Comment by allaway** [comment]
OK- at least for me, creating a conda environment with python=3.8.19 and SigProfilerAssignment=0.1.6 I was able to get this to work!

Here's the `conda list` output in case it helps someone in the future:


```
(sigs38) [ec2-user@ip-10-41-24-211 ~]$ conda list
# packages in environment at /home/ec2-user/miniconda3/envs/sigs38:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
about-time                4.2.1                    pypi_0    pypi
alive-progress            3.1.5                    pypi_0    pypi
ca-certificates           2024.3.11            h06a4308_0
chardet                   5.2.0                    pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
fonttools                 4.53.0                   pypi_0    pypi
grapheme                  0.6.0                    pypi_0    pypi
importlib-resources       6.4.0                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1
libffi                    3.4.4                h6a678d5_1
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libstdcxx-ng              11.2.0               h1234567_1
matplotlib                3.7.5                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
numpy                     1.24.4                   pypi_0    pypi
openssl                   3.0.14               h5eee18b_0
packaging                 24.1                     pypi_0    pypi
pandas                    1.5.3                    pypi_0    pypi
patsy                     0.5.6                    pypi_0    pypi
pdf2image                 1.17.0                   pypi_0    pypi
pillow                    10.3.0                   pypi_0    pypi
pip                       24.0             py38h06a4308_0
psutil                    6.0.0                    pypi_0    pypi
pymupdf                   1.24.7                   pypi_0    pypi
pymupdfb                  1.24.6                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pypdf2                    3.0.1                    pypi_0    pypi
python                    3.8.19               h955ad1f_0
python-dateutil           2.9.0.post0              pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
readline                  8.2                  h5eee18b_0
reportlab                 4.2.2                    pypi_0    pypi
scikit-learn              1.3.2                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                69.5.1           py38h06a4308_0
sigprofilerassignment     0.1.6                    pypi_0    pypi
sigprofilermatrixgenerator 1.2.26                   pypi_0    pypi
sigprofilerplotting       1.3.23                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0
statsmodels               0.14.1                   pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tk                        8.6.14               h39e8969_0
typing-extensions         4.12.2                   pypi_0    pypi
wheel                     0.43.0           py38h06a4308_0
xz                        5.4.6                h5eee18b_1
zipp                      3.19.2                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1
```

**Comment by mdbarnesUCSD** [comment]
Hi @allaway,

I believe this issue arises due to numpy 2.0.0, so if this issue is encountered again please use a version of numpy < v2.0.0. 

Thanks!

**Comment by allaway** [comment]
Thank you!

**Comment by sigven** [comment]
Hi,
Is there any update with respect to the updating the library dependencies, particularly supporting most recent versions of `pandas  (>2.0)`?

best,
Sigve
