### ISSUE TITLE
 Error while providing path to installed TSB files

### ISSUE THREAD

**Issue by pnicolascurie** [AlexandrovLab/SigProfilerAssignment#145]
Hi, I encountered an error while running the `cosmic_fit()` function with the `volume` parameter
Example here: 

```
>>> volume="/data/tmp/pnicolas/tsb"
>>> Analyze.cosmic_fit(samples=in_dir, output=out_dir, input_type="vcf", context_type="96",
...                    collapse_to_SBS96=True, cosmic_version=cosmic_version, exome=exome_value,
...                    genome_build=assembly, signature_database=None,
...                    exclude_signature_subgroups=None, export_probabilities=F,
...                    sample_reconstruction_plots=False, verbose=False, volume=volume)

File   | Status   | Expected MD5                     | Actual MD5                      
---------------------------------------------------------------------------------------
1.txt  | Missing  | ebe083105e7703a49581a36d73732a96 | N/A                             
2.txt  | Missing  | cd65e36dbdf12a8ac3d2c70ebac8cad4 | N/A                             
3.txt  | Missing  | 6c20a7008394f2fa9c304d231a1f391b | N/A                             
4.txt  | Missing  | 5c7443e1678868adadeac0e57558f6e8 | N/A                             
5.txt  | Missing  | 45573232c8097c679503a6598f61e60b | N/A                             
6.txt  | Missing  | cfc137c7434d3a9a872332d405b5c553 | N/A                             
7.txt  | Missing  | 9d8210c22c1962db837e7b62a578975c | N/A                             
8.txt  | Missing  | 665134fd44f21915cbeef955addf89ba | N/A                             
9.txt  | Missing  | 758d0c0c71d8bafbe1ede86587191730 | N/A                             
10.txt | Missing  | 397bb21acff1ca3052ac802f2aee06e0 | N/A                             
11.txt | Missing  | 07707ff8a2a964656469a7be7bb3e576 | N/A                             
12.txt | Missing  | 506d02539075e080ee12ebdf63908080 | N/A                             
13.txt | Missing  | 03ed22f01ab43145733c0b6a647e0560 | N/A                             
14.txt | Missing  | 8b93447086549e476c65699ed813a567 | N/A                             
15.txt | Missing  | cd0dfe9fa78cae2fc7becf8f8ec6c693 | N/A                             
16.txt | Missing  | e17bbb66eb4d6b62b7b0e2fbf062b6a6 | N/A                             
17.txt | Missing  | 8fc95bb3101d024d890aa3543eb454c5 | N/A                             
18.txt | Missing  | a4870628045bb033a90e8c89f818e24d | N/A                             
19.txt | Missing  | 6a9d0c8298f0ba2fa13180e02b969f16 | N/A                             
20.txt | Missing  | aa75d35969cf3956bb4ace7bdc57b34e | N/A                             
21.txt | Missing  | 5d55f5ad6271d6a0d8806876924990f7 | N/A                             
22.txt | Missing  | efdb4e1d23ab7964302b828062a33447 | N/A                             
Y.txt  | Missing  | 3b38c639ad164d60f1a055b46fcd2748 | N/A                             
X.txt  | Missing  | d5edbea3cf5d1716765dd4a7b41b7656 | N/A                             
MT.txt | Missing  | dfd6db5743d399516d5c8dadee5bee78 | N/A                             
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/pnicolas/miniconda3/envs/sigprofiler_new/lib/python3.9/site-packages/SigProfilerAssignment/Analyzer.py", line 132, in cosmic_fit
    decomp.spa_analyze(
  File "/data/users/pnicolas/miniconda3/envs/sigprofiler_new/lib/python3.9/site-packages/SigProfilerAssignment/decomposition.py", line 308, in spa_analyze
    data = datadump.SigProfilerMatrixGeneratorFunc(
  File "/data/users/pnicolas/miniconda3/envs/sigprofiler_new/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGeneratorFunc.py", line 110, in SigProfilerMatrixGeneratorFunc
    raise Exception(
Exception: The specified genome GRCh38 has not been installed
Please refer to the SigProfilerMatrixGenerator README for installation instructions:
	https://github.com/AlexandrovLab/SigProfilerMatrixGenerator
```
There doesn't seem to be any problem with my volume directory file
```
ll /data/tmp/pnicolas/tsb/GRCh38/
total 1.3G
-rw-r--r--. 1 pnicolas curie 128M Jun 10  2019 10.txt
-rw-r--r--. 1 pnicolas curie 129M Jun 10  2019 11.txt
-rw-r--r--. 1 pnicolas curie 128M Jun 10  2019 12.txt
-rw-r--r--. 1 pnicolas curie 110M Jun 10  2019 13.txt
-rw-r--r--. 1 pnicolas curie 103M Jun 10  2019 14.txt
-rw-r--r--. 1 pnicolas curie  98M Jun 10  2019 15.txt
-rw-r--r--. 1 pnicolas curie  87M Jun 10  2019 16.txt
-rw-r--r--. 1 pnicolas curie  80M Jun 10  2019 17.txt
-rw-r--r--. 1 pnicolas curie  77M Jun 10  2019 18.txt
-rw-r--r--. 1 pnicolas curie  56M Jun 10  2019 19.txt
-rw-r--r--. 1 pnicolas curie 238M Jun 10  2019 1.txt
-rw-r--r--. 1 pnicolas curie  62M Jun 10  2019 20.txt
-rw-r--r--. 1 pnicolas curie  45M Jun 10  2019 21.txt
-rw-r--r--. 1 pnicolas curie  49M Jun 10  2019 22.txt
-rw-r--r--. 1 pnicolas curie 231M Jun 10  2019 2.txt
-rw-r--r--. 1 pnicolas curie 190M Jun 10  2019 3.txt
-rw-r--r--. 1 pnicolas curie 182M Jun 10  2019 4.txt
-rw-r--r--. 1 pnicolas curie 174M Jun 10  2019 5.txt
-rw-r--r--. 1 pnicolas curie 163M Jun 10  2019 6.txt
-rw-r--r--. 1 pnicolas curie 152M Jun 10  2019 7.txt
-rw-r--r--. 1 pnicolas curie 139M Jun 10  2019 8.txt
-rw-r--r--. 1 pnicolas curie 132M Jun 10  2019 9.txt
-rw-r--r--. 1 pnicolas curie  215 Aug 26  2019 GRCh38_proportions.txt
-rw-r--r--. 1 pnicolas curie  17K Jun 10  2019 MT.txt
-rw-r--r--. 1 pnicolas curie 149M Jun 10  2019 X.txt
-rw-r--r--. 1 pnicolas curie  55M Jun 10  2019 Y.txt
```
I'm a bit confused with the function `reference_dir()` , it seems to return the default dir location for the annotation though the input for the function is indeed `volume` ?

Best,
Paul-Antoine

**Comment by mdbarnesUCSD** [comment]
Hi @pnicolascurie,

Given that your TSB files are located:
/data/tmp/pnicolas/tsb/GRCh38/

I suspect your `volume` was previously set to `/data/tmp/pnicolas/` and that now when you are setting it to `/data/tmp/pnicolas/tsb` and this is causing the path issue.

Please let me know if fixing your path resolves this. Thanks!

**Comment by pnicolascurie** [comment]
it solved my issue. Thanks!
