### ISSUE TITLE
need help for the flag "signatures"

### ISSUE THREAD

**Issue by sainadfensi** [AlexandrovLab/SigProfilerAssignment#62]
Dear tool developers,

Thanks very much for the most recent updating of the tool. I'm trying 
Sorry that I cannot figure out the error message my self. I will be super appreciated if could have some help from you. 

The code I'm using: 

```
Analyze.decompose_fit(samples=in_path, 
 **signatures**=sigs,
 output=out_path, 
 input_type="vcf",
 genome_build="GRCh38", 
 verbose=False, cosmic_version=3.3,
 make_plots=True,export_probabilities_per_mutation=True,
 exclude_signature_subgroups=exclude_signature_subgroups,
 exome=False)
```

The in_path and out_path are two folders. I'm not sure about the parameter "signatures". I tried use the file provided in the tool for the "signatures", which is "data/Reference_Signatures/GRCh38/COSMIC_v3.3_SBS_GRCh38.txt" but get an error (please see below). 

```
Starting matrix generation for SNVs and DINUCs...Completed! Elapsed time: 1.27 seconds.
Matrices generated for 66 samples with 0 errors. Total of 1489 SNVs, 0 DINUCs, and 0 INDELs were successfully analyzed.

 Decomposing De Novo Signatures  .....
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "SigProfilerAssignment-main/SigProfilerAssignment/Analyzer.py", line 5, in decompose_fit
    decomp.spa_analyze(samples=samples,  output=output, signatures=signatures, signature_database=signature_database,nnls_add_penalty=nnls_add_penalty, nnls_remove_penalty=nnls_remove_penalty, initial_remove_penalty=initial_remove_penalty,genome_build=genome_build, cosmic_version=cosmic_version, make_plots=make_plots, collapse_to_SBS96=collapse_to_SBS96,connected_sigs=connected_sigs, verbose=verbose,decompose_fit_option= True,denovo_refit_option=False,cosmic_fit_option=False,devopts=devopts,new_signature_thresh_hold=new_signature_thresh_hold,exclude_signature_subgroups=exclude_signature_subgroups,exome=exome,input_type=input_type,context_type=context_type,export_probabilities=export_probabilities, export_probabilities_per_mutation=export_probabilities_per_mutation)
  File "SigProfilerAssignment-main/SigProfilerAssignment/decomposition.py", line 497, in spa_analyze
    final_signatures = sub.signature_decomposition(processAvg, mutation_type, layer_directory2, genome_build=genome_build,cosmic_version=cosmic_version,signature_database=signature_database, mutation_context=mutation_context, add_penalty=0.05, connected_sigs=connected_sigs,remove_penalty=0.01, make_decomposition_plots=make_decomposition_plots, originalProcessAvg=originalProcessAvg,new_signature_thresh_hold=new_signature_thresh_hold,sig_exclusion_list=sig_exclusion_list,exome=exome, m_for_subgroups=m_for_subgroups)
  File "SigProfilerAssignment-main/SigProfilerAssignment/decompose_subroutines.py", line 402, in signature_decomposition
    byte_plot = sp.run_PlotDecomposition(originalProcessAvg[denovo_cols],
  File "/opt/homebrew/lib/python3.10/site-packages/pandas/core/frame.py", line 3811, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/opt/homebrew/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6108, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/opt/homebrew/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6171, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['SBS96A'] not in index"
```

Thanks very much for any help! 

Bests,
Jue

**Comment by marcos-diazg** [comment]
Dear Jue,

Thanks so much for reaching out. I understand you would like to perform a mutational signature assignment analysis based on reference COSMIC signatures. If this is the case, please use the `cosmic_fit` function instead of `decompose_fit`. You don't need to provide anything for both the `signatures` and `signature_database` parameters, as the most recent COSMIC v3.3 reference signatures will be used by default for your analysis.

Please feel free to reopen this issue or reach out by email (mdiazgay@health.ucsd.edu) if you have further questions.
