### ISSUE TITLE
Could not run ID signatures

### ISSUE THREAD

**Issue by MeteorLiu96** [AlexandrovLab/SigProfilerAssignment#70]
Hi Raviteja @rvangara

I was planning to repeat the ID signatures by running the SigProfilerAssignment, but met some problems. I tried the `Analyze.cosmic_fit`  with the `context_type="ID"` or `context_type="83"` , but these didn't work. I wonder what I should type in here.

The code and error message showed below:

```
>>> Analyze.cosmic_fit( samples, 
...                     output,
...                     input_type="vcf",
...                     context_type="ID", 
...                     genome_build="GRCh38",
...                     cosmic_version=3.3,
...                     verbose=False,
...                     make_plots=True,
...                     exclude_signature_subgroups=None,
...                     exome=False)
Starting matrix generation for SNVs and DINUCs...Completed! Elapsed time: 338.77 seconds.
Matrices generated for 10071 samples with 0 errors. Total of 2684788 SNVs, 19882 DINUCs, and 0 INDELs were successfully analyzed.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/lib/python3.10/site-packages/SigProfilerAssignment/Analyzer.py", line 11, in cosmic_fit
    decomp.spa_analyze(samples=samples,  output=output, signatures=signatures, signature_database=signature_database,nnls_add_penalty=nnls_add_penalty, nnls_remove_penalty=nnls_remove_penalty, initial_remove_penalty=initial_remove_penalty,genome_build=genome_build, cosmic_version=cosmic_version, make_plots=make_plots, collapse_to_SBS96=collapse_to_SBS96,connected_sigs=connected_sigs, verbose=verbose,decompose_fit_option= False,denovo_refit_option=False,cosmic_fit_option=True,devopts=devopts,exclude_signature_subgroups=exclude_signature_subgroups,exome=exome,input_type=input_type,context_type=context_type,export_probabilities=export_probabilities, export_probabilities_per_mutation=export_probabilities_per_mutation, sample_reconstruction_plots=sample_reconstruction_plots)
  File "/home/user/miniconda3/lib/python3.10/site-packages/SigProfilerAssignment/decomposition.py", line 177, in spa_analyze
    genomes = data[vcf_context]
KeyError: 'ID'
```

**Comment by marcos-diazg** [comment]
Dear @MeteorLiu96,

Thanks for reaching out. As you can see in your output, your vcf files did not contain any indels (`0 INDELs were successfully analyzed.`), so that's the cause of this issue. Please try to use VCF files containing indels, and feel free to reopen the ticket if you still have any issues.

Best,

Marcos
